# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka1:19092
companyName: BNC

cloudHut:
  licenseToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJsaWNlbnNlSWQiOiIxNzQ4ODc2MC1jNzUzLTQ5ODctOWFkOS03ZWJkOWY2NzZkNTEiLCJ1c2VySUQiOiI0MTM0YjA4Mi1lOTViLTQ3NTctYTM5MS0zODU1ZmRhNjJiMWQiLCJwcm9kdWN0VHlwZSI6IkthZmthT3dsIiwiaWF0IjoxNjQxODAxMjM1LCJpc3MiOiJDbG91ZEh1dCJ9.-19vfQ0581MkuXqBrv80J6yYu7qKyO5ti1auWR-ZeNlHbVumM6kwMqrmPAOUu_Ei7UF7EagbbcrMCzvYdLA6bg
login:
  jwtSecret: abcd1234
 
  github:
    enabled: true
    clientId: 056971c6122e201f79df
    clientSecret: f7205815c99a2b991b1b46d72555834061289858
  
business:
  rolesFilepath: /etc/kowl/kowl-business-roles.yaml
  roleBindingsFilepath: /etc/kowl/kowl-business-role-bindings.yaml
  auditLog:
    enabled: false
    additionalHeaders: []
